### numpy array and basics


In [1]:
import numpy as np


In [2]:
marks = np.array([85, 90, 78, 92, 60])
print("marks:",marks)

arr_2d = np.array([[1,1,2],[3,5,6]])
print("2d-Array:",arr_2d)

marks: [85 90 78 92 60]
2d-Array: [[1 1 2]
 [3 5 6]]


### list vs numpy array

In [4]:
py_list = [1,2,3,4]
print("python list multiplication",py_list*2)

print(20*"=")

np_array = np.array([1,2,3]) #element wise multiplication
print("numpy array mul:",np_array*2)

python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
numpy array mul: [2 4 6]


#### Filtering and slicing

In [5]:
passed = marks[marks >= 70]
print("Passed Students:",passed)
print("First 3 Marks:",marks[:3])
print("Last Mark:",marks[-1])

Passed Students: [85 90 78 92]
First 3 Marks: [85 90 78]
Last Mark: 60


#### Built-In math functions


In [6]:
print("Total:",np.sum(marks))
print("Average:",np.mean(marks))
print("Highest:",np.max(marks))
print("Lowest:",np.min(marks))

Total: 405
Average: 81.0
Highest: 92
Lowest: 60


#### 2D Array

In [7]:
sub_marks = np.array([
  [85,90], #student 1
  [78,88], #st 2
  [92,95] #st 3
])
print("Marks Table:\n",sub_marks)

Marks Table:
 [[85 90]
 [78 88]
 [92 95]]


### Row-wise and column-wise operations

In [8]:
# total marks per student => axis1 - row wise, axis 0=> column wise
print("Total per student:",np.sum(sub_marks,axis=1))

print("Average per subject:",np.mean(sub_marks,axis=0))


Total per student: [175 166 187]
Average per subject: [85. 91.]


### more numpy utilities

In [9]:
print(np.arange(1,10))
print(np.zeros((2,3)))
print(np.ones((3,2)))
print(np.sort(marks))

[1 2 3 4 5 6 7 8 9]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[60 78 85 90 92]


### NumPy Score Analyzer

In [10]:
Marks = np.array([75,85,60,45])

# print avg,total,max,min
print("Average:",np.mean(Marks))
print("Total:",np.sum(Marks))
print("Max:",np.max(Marks))
print("Min:",np.min(Marks))

# print student who scored above 60
print("Score above 60:",Marks[Marks > 60])

# 2D array of marks
subject_marks = np.array([
   [75, 80],
    [85, 90],
    [60, 55]
])

# total per student
print("Total per student:", np.sum(subject_marks, axis=1))

# 6. Average per subject
print("Average per subject:", np.mean(subject_marks, axis=0))

Average: 66.25
Total: 265
Max: 85
Min: 45
Score above 60: [75 85]
Total per student: [155 175 115]
Average per subject: [73.33333333 75.        ]


### Array properties

In [14]:
a = np.array([1, 2, 3, 4])
print(a.shape )     # dimensions
print(a.ndim )     # number of dimensions
print(a.size )      # total elements
print(a.dtype )     # data type

(4,)
1
4
int32
